# Generated by Django 3.2 on 2024-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_views', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('most_popular_section', models.CharField(default='Home', max_length=255)),
            ],
        ),
    ]
